name: ServerSystem
description: 'A ServerSystem with a lot of functions and modules.'
author: 'TheMiCraft'
version: '0.1'
main: com.hrens.ServerSystem
commands:
  heal:
    description: Heal Command
    permission: serversystem.heal
    usage: '/heal [name]'
  feed:
    description: Feed Command
    permission: serversystem.feed
    usage: '/feed [name]'
  reboot:
    description: Reboot Command
    permission: serversystem.restart
    usage: '/reboot'
  ban:
    description: Ban Command
    usage: '/ban [name] [ID]'
  unban:
    description: Unban Command
    usage: '/unban [ID]'
  mute:
    description: Mute Command
    usage: '/mute [name] [ID]'
  unmute:
    description: Unmute Command
    usage: '/unmute [ID]'
  check:
    description: Check Command
    permission: serversystem.check
    usage: '/check [name;UUID;ID]'
api-version: 1.19
depend:
  - LuckPerms
libraries:
  - net.dv8tion:JDA:5.0.0-alpha.16
  - org.mongodb:mongodb-driver-sync:4.0.5
  - com.google.code.gson:gson:2.10