name: ServerSystem
description: 'A ServerSystem with a lot of functions and modules.'
author: 'TheMiCraft'
version: '0.1'
main: com.hrens.ServerSystem
api-version: 1.19
commands:
  heal:
    description: Heal Command
    permission: serversystem.heal
  feed:
    description: Feed Command
    permission: serversystem.feed
  reboot:
    description: Reboot Command
    permission: serversystem.restart
  ban:
    description: Ban Command
  unban:
    description: Unban Command
  mute:
    description: Mute Command
  unmute:
    description: Unmute Command
  check:
    description: Check Command
    permission: serversystem.check
softdepend:
  - LuckPerms
libraries:
  - net.dv8tion:JDA:5.0.0-alpha.16
  - org.mongodb:mongodb-driver-sync:4.0.5
  - com.google.code.gson:gson:2.10